<a href="https://colab.research.google.com/github/lawrancesahayasundar-tech/my_first_repo/blob/main/sql_query.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import sqlite3

# URLs
customers_url = "https://raw.githubusercontent.com/graphql-compose/graphql-compose-examples/master/examples/northwind/data/csv/customers.csv"
orders_url = "https://raw.githubusercontent.com/graphql-compose/graphql-compose-examples/master/examples/northwind/data/csv/orders.csv"

# Load data
customers_df = pd.read_csv(customers_url)
orders_df = pd.read_csv(orders_url)

# Create SQLite DB
conn = sqlite3.connect(":memory:")

# Store tables
customers_df.to_sql("customers", conn, index=False, if_exists="replace")
orders_df.to_sql("orders", conn, index=False, if_exists="replace")

print("Data loaded successfully!")

Data loaded successfully!

In [2]:
query1 = """
SELECT
    CustomerID,
    COUNT(OrderID) AS order_count,
    SUM(Freight) AS total_freight,
    AVG(Freight) AS avg_freight
FROM orders
GROUP BY CustomerID
ORDER BY total_freight DESC
"""

result1 = pd.read_sql_query(query1, conn)

# Display top 10
result1.head(10)

  customerID  order_count  total_freight  avg_freight
0      SAVEA           31        6683.70   215.603226
1      ERNSH           30        6205.39   206.846333
2      QUICK           28        5605.63   200.201071
3      HUNGO           19        2755.24   145.012632
4      RATTC           18        2134.21   118.567222
5      QUEEN           13        1982.70   152.515385
6      FOLKO           19        1678.08    88.320000
7      BERGS           18        1559.52    86.640000
8      FRANK           15        1403.44    93.562667
9      MEREP           13        1394.22   107.247692

In [3]:
query2A = """
SELECT
    CustomerID,
    COUNT(OrderID) AS high_freight_orders
FROM orders
WHERE Freight > 50
GROUP BY CustomerID
"""

result2A = pd.read_sql_query(query2A, conn)
result2A.head()

  customerID  high_freight_orders
0      ALFKI                    2
1      ANTON                    2
2      AROUT                    2
3      BERGS                   11
4      BLAUS                    1

In [4]:
query2B = """
SELECT
    CustomerID,
    SUM(Freight) AS total_freight
FROM orders
GROUP BY CustomerID
HAVING SUM(Freight) > 500
"""

result2B = pd.read_sql_query(query2B, conn)
result2B.head()

  customerID  total_freight
0      BERGS        1559.52
1      BLONP         623.66
2      BONAP        1357.87
3      BOTTM         793.95
4      EASTC         832.34

In [5]:
query3_inner = """
SELECT
    c.CompanyName,
    c.Country,
    COUNT(o.OrderID) AS order_count,
    SUM(o.Freight) AS total_freight
FROM customers c
INNER JOIN orders o
ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID
ORDER BY total_freight DESC
"""

result3_inner = pd.read_sql_query(query3_inner, conn)
result3_inner.head()

                    companyName  country  order_count  total_freight
0            Save-a-lot Markets      USA           31        6683.70
1                  Ernst Handel  Austria           30        6205.39
2                    QUICK-Stop  Germany           28        5605.63
3  Hungry Owl All-Night Grocers  Ireland           19        2755.24
4    Rattlesnake Canyon Grocery      USA           18        2134.21

In [6]:
query3_left = """
SELECT
    c.CompanyName,
    c.Country,
    COUNT(o.OrderID) AS order_count,
    COALESCE(SUM(o.Freight), 0) AS total_freight
FROM customers c
LEFT JOIN orders o
ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID
ORDER BY total_freight DESC
"""

result3_left = pd.read_sql_query(query3_left, conn)
result3_left.head()

                    companyName  country  order_count  total_freight
0            Save-a-lot Markets      USA           31        6683.70
1                  Ernst Handel  Austria           30        6205.39
2                    QUICK-Stop  Germany           28        5605.63
3  Hungry Owl All-Night Grocers  Ireland           19        2755.24
4    Rattlesnake Canyon Grocery      USA           18        2134.21